spring.datasource.url=jdbc:postgresql://db:5432/security_findings
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.jackson.time-zone=UTC

app.jwt.secret=change-this-secret-to-32-characters-minimum
app.jwt.expiration-seconds=3600
app.evidence.storage-path=storage/evidence

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
